---
-- Scripts courses
---
INSERT INTO `courses` (`code`, `name`, `term`, `ue_aa`, `ects`, `block`, `abbreviation`) VALUES
('I1010', 'Algorithmique', 'Q1', 'UE', '6', 'bloc1', 'Algo\r'),
('I1020', 'Analyse et Programmation Orientée Objet', 'Q1', 'UE', '5', 'bloc1', 'APOO\r'),
('I1030', 'Analyse et Architecture des Données', 'Q2', 'UE', '5', 'bloc1', 'Ianarch\r'),
('I1040', 'Structures de Données', 'Q2', 'UE', '6', 'bloc1', 'SD\r'),
('I1050', 'Programmation Web : Bases', 'Q2', 'UE', '5', 'bloc1', 'Web 1\r'),
('I1060', 'Introduction aux Systèmes d\'Exploitation', 'Q2', 'UE', '5', 'bloc1', 'OS 1\r'),
('I106A', 'Théorie des systèmes d’exploitation', 'Q2', 'AA', '2,5', 'bloc1', 'OS (Th)\r'),
('I106B', 'Introduction à Linux', 'Q2', 'AA', '2,5', 'bloc1', 'Linux\r'),
('I1070', 'Fonctionnement des Ordinateurs', 'Q1', 'UE', '6', 'bloc1', 'FO\r'),
('I1080', 'L’Entreprise et ses Relations avec le Monde Economique', 'Q1', 'UE', '5', 'bloc1', '\r'),
('I108A', 'Comptabilité', 'Q1', 'AA', '3', 'bloc1', 'Comptabilité\r'),
('I108B', 'Economie et Fonctionnement de l\'entreprise', 'Q1', 'AA', '3', 'bloc1', 'Economie\r'),
('I1090', 'Mathématiques 1 : Outils Fondamentaux', 'Q1', 'UE', '4', 'bloc1', 'Math 1\r'),
('I1100', 'Mathématiques 2 : Structures Avancées', 'Q2', 'UE', '6', 'bloc1', 'Math 2\r'),
('I1110', 'Projet de Développement Web', 'Q2', 'UE', '3', 'bloc1', 'Projet Web\r'),
('I1120', 'Anglais 1', 'Q12', 'UE', '4', 'bloc1', 'Anglais 1\r'),
('I2010', 'Langage C', 'Q1', 'UE', '5', 'bloc2', 'Langage C\r'),
('I2020', 'Programmation Avancée en Java', 'Q2', 'UE', '4', 'bloc2', '\r'),
('I202A', 'Ateliers java', 'Q1', 'AA', '2,5', 'bloc2', 'Ateliers java\r'),
('I202B', 'Structures de données', 'Q1', 'AA', '1,5', 'bloc2', 'SD\r'),
('I2030', 'Analyse et Conception', 'Q1', 'UE', '6', 'bloc2', '\r'),
('I203A', 'Cahier des charges', 'Q1', 'AA', '2', 'bloc2', 'Cahier charges\r'),
('I203B', 'Concepts Orientés Objet', 'Q1', 'AA', '2', 'bloc2', 'COO\r'),
('I203C', 'UML', 'Q1', 'AA', '2', 'bloc2', 'UML\r'),
('I2040', 'Gestion de Données', 'Q1', 'UE', '6', 'bloc2', '\r'),
('I2050', 'Programmation Web : Avancé', 'Q1', 'UE', '6', 'bloc2', '\r'),
('I205A', 'Data Exchange Format', 'Q1', 'AA', '2', 'bloc2', 'XML\r'),
('I205B', 'Javascript', 'Q1', 'AA', '3', 'bloc2', 'JavaScript\r'),
('I205C', 'Ergonomie Web', 'Q1', 'AA', '1', 'bloc2', 'Ergonomie Web\r'),
('I2060', 'Systèmes Informatiques : Principes et Protocoles', 'Q1', 'UE', '4', 'bloc2', '\r'),
('I206A', 'Système d\'exploitation', 'Q1', 'AA', '2', 'bloc2', 'OS\r'),
('I206B', 'IPP, Couches Hautes', 'Q1', 'AA', '2', 'bloc2', 'Télécom\r'),
('I2070', 'Internet : Principes et Protocoles Avancés', 'Q2', 'UE', '3', 'bloc2', '\r'),
('I207A', 'Internet', 'Q2', 'AA', '2', 'bloc2', 'Internet\r'),
('I207B', 'Programmation réseau', 'Q2', 'AA', '1', 'bloc2', 'Prog réseau\r'),
('I2080', 'Organisation des Entreprises', 'Q2', 'UE', '6', 'bloc2', '\r'),
('I208A', 'Organisation des entreprises', 'Q2', 'AA', '4', 'bloc2', 'orga \r'),
('I208B', 'Stage d’observation', 'Q2', 'AA', '2', 'bloc2', 'Stage Obs\r'),
('I2090', 'Design d\'Applications d\'Entreprise', 'Q2', 'UE', '6', 'bloc2', '\r'),
('I209A', 'Projet d’application d’entreprise', 'Q2', 'AA', '4', 'bloc2', 'projet DAE\r'),
('I209B', 'Architecture d\'Application Multithread', 'Q2', 'AA', '2', 'bloc2', 'AAM\r'),
('I2100', 'Unix', 'Q2', 'UE', '5', 'bloc2', '\r'),
('I210A', 'Unix : théorie', 'Q2', 'AA', '2', 'bloc2', 'Unix (th)\r'),
('I210B', 'Unix : Exercices', 'Q2', 'AA', '3', 'bloc2', 'Unix (ex)\r'),
('I2110', 'Informatique Mobile', 'Q2', 'UE', '4', 'bloc2', 'Mobile\r'),
('I2120', 'Anglais 2', 'Q12', 'UE', '5', 'bloc2', 'Anglais 2\r'),
('I3010', 'Programmation Java : Questions Spéciales', 'Q1', 'UE', '5', 'bloc3', '\r'),
('I301A', 'Patrons de conception', 'Q1', 'AA', 'x', 'bloc3', 'Pattern\r'),
('I301B', 'Développement d’Applications Entreprise', 'Q1', 'AA', 'x', 'bloc3', 'DAE\r'),
('I3020', 'Administration et Sécurité des Systèmes', 'Q1', 'UE', '5', 'bloc3', '\r'),
('I302A', 'Administration d\'un système Linux (Théorie)', 'Q1', 'AA', 'x', 'bloc3', 'Adm Unix (th)\r'),
('I302B', 'Administration d\'un système Linux (exercices)', 'Q1', 'AA', 'x', 'bloc3', 'Adm Unix (ex)\r'),
('I302C', 'Administration windows', 'Q1', 'AA', 'x', 'bloc3', 'windows\r'),
('I3030', 'Administration et Sécurité des Réseaux', 'Q1', 'UE', '5', 'bloc3', '\r'),
('I303A', 'Internet-Intranet', 'Q1', 'AA', 'x', 'bloc3', 'Inter-Intranet\r'),
('I303B', 'Laboratoire des réseaux', 'Q1', 'AA', 'x', 'bloc3', 'Labo réseaux\r'),
('I303C', 'Sécurité', 'Q1', 'AA', 'x', 'bloc3', '\r'),
('I3040', 'Organisation et Gestion des Entreprises', 'Q1', 'UE', '5', 'bloc3', '\r'),
('I304A', 'Big Data', 'Q1', 'AA', 'x', 'bloc3', 'Big Data\r'),
('I304B', 'Gestion de projets Agile', 'Q1', 'AA', 'x', 'bloc3', 'Projets Agile\r'),
('I304C', 'Droit et déontologie', 'Q1', 'AA', 'x', 'bloc3', 'droit\r'),
('I3050', 'Anglais 3', 'Q1', 'UE', '2', 'bloc3', 'Anglais 3\r'),
('I3060', 'Projet de fin d\'études', 'Q2', 'UE', '2', 'bloc3', 'projet\r'),
('I3070', 'Projet de fin d\'études - .NET', 'Q2', 'UE', '2', 'bloc3', 'projet\r'),
('I3080', 'Activité d\'Intégration en Milieu Professionnel', 'Q2', 'UE', '28', 'bloc3', 'stage  \r'),
('I308A', 'Stage en Entreprise', 'Q2', 'AA', 'x', 'bloc3', '\r'),
('I308B', 'Rédaction de documentation technique', 'Q2', 'AA', 'x', 'bloc3', '\r'),
('I308C', 'Présentation et défense du TFE', 'Q2', 'AA', 'x', 'bloc3', '\r'),
('I308D', 'Gestion de Projets', 'Q2', 'AA', 'x', 'bloc3', 'Gestion projets\r'),
('I3090', 'Développement à l\'aide d\'un moteur de jeux', 'Q1', 'UE', '4', 'bloc3', 'unity\r'),
('I3100', 'Intelligence Artificielle', 'Q1', 'UE', '4', 'bloc3', '\r'),
('I310A', 'Programmation Fonctionnelle, Logique et par Contraintes', 'Q1', 'AA', 'x', 'bloc3', 'prog fonct.\r'),
('I310B', 'Intelligence artificielle : Bases', 'Q1', 'AA', 'x', 'bloc3', 'IA\r'),
('I3110', 'Framework .Net', 'Q1', 'UE', '4', 'bloc3', '\r'),
('I311A', 'C#.NET', 'Q1', 'AA', 'x', 'bloc3', 'C#\r'),
('I311B', 'ASP.NET', 'Q1', 'AA', 'x', 'bloc3', 'ASP.NET\r'),
('I3120', 'Progiciel de Gestion Intégré', 'Q1', 'UE', '4', 'bloc3', 'SAP\r'),
('I3130', 'Programmation Web : Questions Spéciales', 'Q1', 'UE', '4', 'bloc3', 'Web 3\r');

---
-- Scripts series
---

INSERT INTO `series` (`serie_num`, `block`) VALUES
(1, 'bloc1'),
(2, 'bloc1'),
(3, 'bloc1'),
(1, 'bloc2'),
(2, 'bloc2'),
(3, 'bloc2'),
(1, 'bloc3'),
(2, 'bloc3'),
(3, 'bloc3'),
(4, 'bloc1');

---
-- Scripts agenda
---

INSERT INTO `weeks` (`week_id`, `start_date`, `term`) VALUES
(1, '19/09/2016', 1),
(2, '26/09/2016', 1),
(3, '3/10/2016', 1),
(4, '10/10/2016', 1),
(5, '17/10/2016', 1),
(6, '24/10/2016', 1),
(7, '7/11/2016', 1);

---
-- Scripts teachers
---


INSERT INTO `teachers` (`teacher_mail`, `name`, `first_name`, `responsability`) VALUES
('annick.dupont@vinci.be', 'Dupont', 'Annick', 'No responsability'),
('anthony.legrand@vinci.be', 'Legrand', 'Anthony', 'No responsability'),
('bernard.frank@vinci.be', 'Frank', 'Bernard', 'No responsability'),
('bernard.henriet@vinci.be', 'Henriet', 'Bernard', 'blocs\r'),
('brigitte.binot@vinci.be', 'Binot', 'Brigitte', 'No responsability'),
('brigitte.lehmann@vinci.be', 'Lehmann', 'Brigitte', 'No responsability'),
('christophe.damas@vinci.be', 'Damas', 'Christophe', 'bloc2\r'),
('colette.demuylder@vinci.be', 'De Muylder', 'Colette', 'No responsability'),
('donatien.grolaux@vinci.be', 'Grolaux', 'Donatien', 'bloc3\r'),
('emmeline.leconte@vinci.be', 'Leconte', 'Emmeline', 'blocs\r'),
('gregory.seront@vinci.be', 'Seront', 'Gregory', 'true'),
('jeanluc.collinet@ipl.be', 'Collinet', 'Jean-Luc', 'bloc1\r'),
('jose.vandermeulen@vinci.be', 'Vandermeulen', 'José', 'No responsability'),
('julien.federinov@vinci.be', 'Federinov', 'Julien', 'No responsability'),
('laurent.leleux@vinci.be', 'Leleux', 'Laurent', 'No responsability'),
('michel.debacker@vinci.be', 'Debacker', 'Michel', 'No responsability'),
('olivier.choquet@vinci.be', 'Choquet', 'Olivier', 'No responsability'),
('philippe.vaneerdenbrugghe@vinci.be', 'Vaneerdenbrugghe', 'Philippe', 'No responsability'),
('sonia.belina@vinci.be', 'Belina-Podgaetsky', 'Sonia', 'No responsability'),
('stephanie.ferneeuw@vinci.be', 'Ferneeuw', 'Stéphanie', 'No responsability');


---
-- Scripts sessions
---

INSERT INTO `sessions_type` (`session_id`, `code`, `session_name`, `type`) VALUES
(55909, 'I1050', 'PHP C', 'x'),
(89944, 'I1050', 'PHP B', 'note'),
(195562, 'I1050', 'PHP A', 'x');

---
-- Scripts students
---

INSERT INTO `students` (`student_mail`, `serie_num`, `name`, `first_name`, `block`) VALUES
('abdelhak.bakalem@student.vinci.be', NULL, 'BAKALEM', 'Abdelhak', 'Bloc2'),
('adeline.duterre@student.vinci.be', NULL, 'DUTERRE', 'Adeline', 'Bloc2'),
('adnan.jlassi@student.vinci.be', 2, 'JLASSI', 'Adnan', 'Bloc1'),
('adrian.dellavallemorinigo@student.vinci.be', 2, 'DELLAVALLE MORINIGO', 'Adrian', 'Bloc1'),
('adrian.gajda@student.vinci.be', 3, 'GAJDA', 'Adrian', 'Bloc1'),
('ahmad.bashir@student.vinci.be', NULL, 'BASHIR', 'Ahmad', 'Bloc2'),
('alan.buelinckx@student.vinci.be', 4, 'BUELINCKX', 'Alan', 'Bloc1'),
('albinot.fetahi@student.vinci.be', 3, 'Fetahi', 'Albinot', 'Bloc1'),
('alexandre.coste-gandrey@student.vinci.be', NULL, 'COSTE-GANDREY', 'Alexandre', 'Bloc2'),
('alexandre.hardi@student.vinci.be', NULL, 'HARDI', 'Alexandre', 'Bloc2'),
('alexandre.maniet@student.vinci.be', NULL, 'MANIET', 'Alexandre', 'Bloc2'),
('alexandre.maroun@student.vinci.be', 1, 'Maroun', 'Alexandre', 'Bloc1'),
('alexandre.sousadossantos@student.vinci.be', NULL, 'SOUSA DOS SANTOS', 'Alexandre', 'Bloc2'),
('alexandre.wacquier@student.vinci.be', 2, 'WACQUIER', 'Alexandre', 'Bloc1'),
('alexis.rifaut@student.vinci.be', 3, 'RIFAUT', 'Alexis', 'Bloc1'),
('ali.godazendeh@student.vinci.be', 4, 'GODAZENDEH', 'Ali', 'Bloc1'),
('amandine.vangrunderbeeck@student.vinci.be', NULL, 'VAN GRUNDERBEECK', 'Amandine', 'Bloc2'),
('amatus.umugabe@student.vinci.be', 3, 'UMUGABE', 'Amatus', 'Bloc1'),
('amaury.evrard@student.vinci.be', NULL, 'EVRARD', 'Amaury', 'Bloc3'),
('anas.hammani@student.vinci.be', 2, 'HAMMANI', 'Anas', 'Bloc1'),
('andre.daspremont@student.vinci.be', NULL, 'DASPREMONT', 'André', 'Bloc3'),
('andrea.occhilupo@student.vinci.be', 1, 'OCCHILUPO', 'Andrea', 'Bloc1'),
('andy.desmedt@student.vinci.be', 2, 'De Smedt', 'Andy', 'Bloc1'),
('andy.voiturier@student.vinci.be', 3, 'VOITURIER', 'Andy', 'Bloc1'),
('angecedrick.angaman@student.vinci.be', 4, 'ANGAMAN', 'Ange Cedrick', 'Bloc1'),
('anthony.maton@student.vinci.be', NULL, 'MATON', 'Anthony', 'Bloc3'),
('anthony.pierre@student.vinci.be', NULL, 'PIERRE', 'Anthony', 'Bloc2'),
('anthony.pyck@student.vinci.be', NULL, 'PYCK', 'Anthony', 'Bloc2'),
('anthony.vancampenhault@student.vinci.be', NULL, 'VANCAMPENHAULT', 'Anthony', 'Bloc2'),
('antoine.colet@student.vinci.be', NULL, 'COLET', 'Antoine', 'Bloc3'),
('antoine.debroux@student.vinci.be', 3, 'DEBROUX', 'Antoine', 'Bloc1'),
('antoine.deroose@student.vinci.be', 2, 'DE ROOSE', 'Antoine', 'Bloc1'),
('antoine.lambricht@student.vinci.be', NULL, 'LAMBRICHT', 'Antoine', 'Bloc2'),
('antoine.maniet@student.vinci.be', NULL, 'MANIET', 'Antoine', 'Bloc2'),
('antoine.ramelot@student.vinci.be', 1, 'RAMELOT', 'Antoine', 'Bloc1'),
('antoine.verlant@student.vinci.be', NULL, 'VERLANT', 'Antoine', 'Bloc3'),
('antonin.riche@student.vinci.be', NULL, 'RICHE', 'Antonin', 'Bloc2'),
('arnaud.bourez@student.vinci.be', 2, 'BOUREZ', 'Arnaud', 'Bloc1'),
('arnaud.deboeck@student.vinci.be', 3, 'DE BOECK', 'Arnaud', 'Bloc1'),
('arnaud.etienne@student.vinci.be', NULL, 'ETIENNE', 'Arnaud', 'Bloc2'),
('arnaud.poullet@student.vinci.be', NULL, 'POULLET', 'Arnaud', 'Bloc1'),
('arnaud.rochez@student.vinci.be', NULL, 'ROCHEZ', 'Arnaud', 'Bloc3'),
('arnaud.terryn@student.vinci.be', NULL, 'TERRYN', 'Arnaud', 'Bloc1'),
('arthur.speicher@student.vinci.be', NULL, 'SPEICHER', 'Arthur', 'Bloc1'),
('artjam.umanyan@student.vinci.be', NULL, 'Umanyan', 'Artjam', 'Bloc1'),
('arturo.mozzon@student.vinci.be', NULL, 'MOZZON', 'Arturo', 'Bloc1'),
('augustin.demeeusdargenteuil@student.vinci.be', NULL, 'de MEEuS d\'ARGENTEUIL', 'Augustin', 'Bloc1'),
('aurelien.lefebvre@student.vinci.be', NULL, 'LEFEBVRE', 'Aurélien', 'Bloc3'),
('azeddine.mansour@student.vinci.be', NULL, 'Mansour', 'Azeddine', 'Bloc1'),
('badreddine.lahrichi@student.vinci.be', NULL, 'LAHRICHI', 'Badreddine', 'Bloc1'),
('bastien.dessy@student.vinci.be', NULL, 'DESSY', 'Bastien', 'Bloc1'),
('bastien.dossantos@student.vinci.be', NULL, 'DOS SANTOS', 'Bastien', 'Bloc3'),
('benjamin.berge@student.vinci.be', NULL, 'BERGÉ', 'Benjamin', 'Bloc2'),
('benjamin.debosscher@student.vinci.be', NULL, 'De Bosscher', 'Benjamin', 'Bloc1'),
('benjamin.declercq@student.vinci.be', NULL, 'DECLERCQ', 'Benjamin', 'Bloc2'),
('benjamin.pierre@student.vinci.be', NULL, 'PIERRE', 'Benjamin', 'Bloc2'),
('bill.brancart@student.vinci.be', NULL, 'BRANCART', 'Bill', 'Bloc3'),
('bouchra.kh\'leeh@student.vinci.be', NULL, 'KH\' LEEH', 'Bouchra', 'Bloc1'),
('brian.diazalvarez@student.vinci.be', NULL, 'Diaz Alvarez', 'Brian', 'Bloc1'),
('brieuc.seeger@student.vinci.be', NULL, 'SEEGER', 'Brieuc', 'Bloc1'),
('bunyamin.aslan@student.vinci.be', NULL, 'ASLAN', 'Bunyamin', 'Bloc1'),
('burim.kastrati@student.vinci.be', NULL, 'KASTRATI', 'Burim', 'Bloc1'),
('cedric.martin@student.vinci.be', NULL, 'MARTIN', 'Cedric', 'Bloc1'),
('cedric.tavernier@student.vinci.be', NULL, 'TAVERNIER', 'Cedric', 'Bloc2'),
('chamil.chakhabov@student.vinci.be', NULL, 'CHAKHABOV', 'Chamil', 'Bloc1'),
('christian.mendesrosa@student.vinci.be', NULL, 'MENDES ROSA', 'Christian', 'Bloc3'),
('christophe.bortier@student.vinci.be', NULL, 'BORTIER', 'Christophe', 'Bloc2'),
('christophe.driessen@student.vinci.be', NULL, 'DRIESSEN', 'Christophe', 'Bloc2'),
('christophe.jabbour@student.vinci.be', NULL, 'Jabbour', 'Christophe', 'Bloc1'),
('christopher.castel@student.vinci.be', NULL, 'CASTEL', 'Christopher', 'Bloc1'),
('christopher.sacre@student.vinci.be', NULL, 'SACRÉ', 'Christopher', 'Bloc2'),
('clement.dujardin@student.vinci.be', NULL, 'du JARDIN', 'Clément', 'Bloc2'),
('colin.vandenbrande@student.vinci.be', NULL, 'VAN DEN BRANDE', 'Colin', 'Bloc1'),
('corenthin.dubois@student.vinci.be', NULL, 'DUBOIS', 'Corenthin', 'Bloc2'),
('cyril.hennen@student.vinci.be', NULL, 'HENNEN', 'Cyril', 'Bloc1'),
('cyrille.hourant@student.vinci.be', NULL, 'HOURANT', 'Cyrille', 'Bloc1'),
('damian.szacun@student.vinci.be', NULL, 'SZACUN', 'Damian', 'Bloc1'),
('damien.kech@student.vinci.be', NULL, 'KECH', 'Damien', 'Bloc3'),
('damien.meur@student.vinci.be', NULL, 'MEUR', 'Damien', 'Bloc2'),
('damien.syemons@student.vinci.be', NULL, 'SYEMONS', 'Damien', 'Bloc3'),
('dani.rochaazevedo@student.vinci.be', NULL, 'Rocha Azevedo', 'Dani', 'Bloc1'),
('dattoan.nguyen@student.vinci.be', NULL, 'NGUYEN', 'Dat Toan', 'Bloc2'),
('dawid.tararuj@student.vinci.be', NULL, 'Tararuj', 'Dawid', 'Bloc1'),
('debrah.tinsia@student.vinci.be', NULL, 'TINSIA', 'Debrah', 'Bloc2'),
('dejvi.kurti@student.vinci.be', NULL, 'KURTI', 'Dejvi', 'Bloc1'),
('delanoe.pirard@student.vinci.be', NULL, 'PIRARD', 'Delanoe', 'Bloc3'),
('diana.grama@student.vinci.be', NULL, 'Grama', 'Diana', 'Bloc1'),
('diego.nuezsoriano@student.vinci.be', NULL, 'NUEZ SORIANO', 'Diego', 'Bloc2'),
('djama.omar@student.vinci.be', NULL, 'OMAR', 'Djama', 'Bloc1'),
('dorian.gruselin@student.vinci.be', NULL, 'GRUSELIN', 'Dorian', 'Bloc1'),
('driss.bengeloune@student.vinci.be', NULL, 'BEN GELOUNE', 'Driss', 'Bloc1'),
('driss.vandenheede@student.vinci.be', NULL, 'VANDENHEEDE', 'Driss', 'Bloc1'),
('dylan.divito@student.vinci.be', NULL, 'DI VITO', 'Dylan', 'Bloc3'),
('egide.kabanza@student.vinci.be', NULL, 'KABANZA', 'Egide', 'Bloc1'),
('ekrem.ozturk@student.vinci.be', NULL, 'Özturk', 'Ekrem', 'Bloc1'),
('emanuel.peroni@student.vinci.be', NULL, 'PERONI', 'Emanuel', 'Bloc1'),
('emilien.durieu@student.vinci.be', NULL, 'DURIEU', 'Emilien', 'Bloc3'),
('emre.tasyurek@student.vinci.be', NULL, 'TASYuREK', 'Emre', 'Bloc2'),
('fabian.teichmann@student.vinci.be', NULL, 'TEICHMANN', 'Fabian', 'Bloc1'),
('fabio.grumiro@student.vinci.be', NULL, 'GRUMIRO', 'Fabio', 'Bloc3'),
('fany.bottemanne@student.vinci.be', NULL, 'BOTTEMANNE', 'Fany', 'Bloc3'),
('felix.jacoby@student.vinci.be', NULL, 'JACOBY', 'Félix', 'Bloc2'),
('filip.lolic@student.vinci.be', NULL, 'Lolic', 'Filip', 'Bloc1'),
('florian.morel@student.vinci.be', NULL, 'MOREL', 'Florian', 'Bloc3'),
('florian.sollami@student.vinci.be', NULL, 'SOLLAMI', 'Florian', 'Bloc1'),
('florian.timmermans@student.vinci.be', NULL, 'TIMMERMANS', 'Florian', 'Bloc1'),
('florian.verdonck@student.vinci.be', NULL, 'VERDONCK', 'Florian', 'Bloc1'),
('françois.pecheur@student.vinci.be', NULL, 'Pecheur', 'François', 'Bloc1'),
('françois.pochet@student.vinci.be', NULL, 'Pochet', 'François', 'Bloc1'),
('frederic.hubert@student.vinci.be', NULL, 'HUBERT', 'Frédéric', 'Bloc2'),
('gabriel.curatolo@student.vinci.be', NULL, 'CURATOLO', 'Gabriel', 'Bloc1'),
('gabriel.delhaye@student.vinci.be', NULL, 'DELHAYE', 'Gabriel', 'Bloc2'),
('gabriel.haba@student.vinci.be', NULL, 'HABA', 'Gabriel', 'Bloc2'),
('gael.kifoumbi@student.vinci.be', NULL, 'KIFOUMBI ', 'Gael', 'Bloc1'),
('gael.leroy@student.vinci.be', NULL, 'LEROY', 'Gael', 'Bloc3'),
('gaspard.devillenfagnedevogelsanck@student.vinci.be', NULL, 'de VILLENFAGNE de VOGELSANCK', 'Gaspard', 'Bloc2'),
('gauthier.grandhenry@student.vinci.be', NULL, 'GRANDHENRY', 'Gauthier', 'Bloc1'),
('gauthier.lallemand@student.vinci.be', NULL, 'LALLEMAND', 'Gauthier', 'Bloc2'),
('geoffroy.frennet@student.vinci.be', NULL, 'FRENNET', 'Geoffroy', 'Bloc1'),
('gilles.renson@student.vinci.be', NULL, 'RENSON', 'Gilles', 'Bloc2'),
('gorgis.yaramis@student.vinci.be', NULL, 'YARAMIS', 'Gorgis', 'Bloc1'),
('gregory.decraemer@student.vinci.be', NULL, 'DECRAEMER', 'Grégory', 'Bloc1'),
('guillaume.lion@student.vinci.be', NULL, 'LION', 'Guillaume', 'Bloc1'),
('guillaume.wery@student.vinci.be', NULL, 'WERY', 'Guillaume', 'Bloc1'),
('guy.vassart@student.vinci.be', NULL, 'VASSART', 'Guy', 'Bloc1'),
('hakan.poyraz@student.vinci.be', NULL, 'POYRAZ', 'Hakan', 'Bloc1'),
('halil.top@student.vinci.be', NULL, 'TOP', 'Halil', 'Bloc1'),
('hamza.guerrouaj@student.vinci.be', NULL, 'GUERROUAJ', 'Hamza', 'Bloc1'),
('hamza.mahmoudi@student.vinci.be', NULL, 'MAHMOUDI', 'Hamza', 'Bloc1'),
('hamza.mounir@student.vinci.be', NULL, 'MOUNIR', 'Hamza', 'Bloc3'),
('hicham.elasri@student.vinci.be', NULL, 'EL ASRI', 'Hicham', 'Bloc1'),
('hugues.demathelindepapigny@student.vinci.be', NULL, 'de Mathelin de Papigny', 'Hugues', 'Bloc1'),
('ibrahim.mourade@student.vinci.be', NULL, 'MOURADE', 'Ibrahim', 'Bloc2'),
('ikram.noorzaai@student.vinci.be', NULL, 'NOORZAAI', 'Ikram', 'Bloc1'),
('ilias.barrani@student.vinci.be', NULL, 'BARRANI', 'Ilias', 'Bloc1'),
('ilias.jafar@student.vinci.be', NULL, 'JAFAR', 'Ilias', 'Bloc1'),
('ilias.tellihi@student.vinci.be', NULL, 'TELLIHI', 'Ilias', 'Bloc1'),
('ismael.elfkihbenahmed@student.vinci.be', NULL, 'El F\'Kih Ben Ahmed', 'Ismael', 'Bloc1'),
('ismaila.abdoulahiadamou@student.vinci.be', NULL, 'ABDOULAHI ADAMOU', 'Ismaila', 'Bloc1'),
('iulian.avram@student.vinci.be', NULL, 'Avram', 'Iulian', 'Bloc1'),
('ivan.pessers@student.vinci.be', NULL, 'PESSERS', 'Ivan', 'Bloc3'),
('jacques.yakoub@student.vinci.be', NULL, 'YAKOUB', 'Jacques', 'Bloc3'),
('jean-bosco.rwibutso@student.vinci.be', NULL, 'RWIBUTSO', 'Jean-Bosco', 'Bloc2'),
('jean-françois.cochart@student.vinci.be', NULL, 'COCHART', 'Jean-François', 'Bloc2'),
('jean-françois.schweisthal@student.vinci.be', NULL, 'SCHWEISTHAL', 'Jean-François', 'Bloc3'),
('jean-pacifique.mbonyincungu@student.vinci.be', NULL, 'MBONYINCUNGU ', 'Jean-Pacifique', 'Bloc3'),
('jean.dubuisson@student.vinci.be', NULL, 'DUBUISSON', 'Jean', 'Bloc1'),
('jeremy.balcinhasgodinho@student.vinci.be', NULL, 'BALCINHAS GODINHO', 'Jérémy', 'Bloc1'),
('jeremy.holodiline@student.vinci.be', NULL, 'Holodiline', 'Jeremy', 'Bloc1'),
('jeremy.vandermotte@student.vinci.be', NULL, 'VANDER MOTTE', 'Jérémy', 'Bloc1'),
('jerome.deborsu@student.vinci.be', NULL, 'DEBORSU', 'Jérome', 'Bloc1'),
('jimmy.delacruzmallada@student.vinci.be', NULL, 'DE LA CRUZ MALLADA', 'Jimmy', 'Bloc3'),
('joachim.vranken@student.vinci.be', NULL, 'VRANKEN', 'Joachim', 'Bloc1'),
('joelle.maffomeleu@student.vinci.be', NULL, 'MAFFO MELEU', 'Joelle', 'Bloc1'),
('johann.buxant@student.vinci.be', NULL, 'BUXANT', 'Johann', 'Bloc2'),
('johnny.la@student.vinci.be', NULL, 'LA', 'Johnny', 'Bloc2'),
('johnny.steutgens@student.vinci.be', NULL, 'STEUTGENS', 'Johnny', 'Bloc1'),
('jolan.wathelet@student.vinci.be', NULL, 'WATHELET', 'Jolan', 'Bloc2'),
('jonathan.visiedogil@student.vinci.be', NULL, 'Visiedo Gil', 'Jonathan', 'Bloc1'),
('joris.pluton@student.vinci.be', NULL, 'PLUTON', 'Joris', 'Bloc1'),
('jozef.sako@student.vinci.be', NULL, 'SAKO', 'Jozef', 'Bloc1'),
('julien.doyen@student.vinci.be', NULL, 'DOYEN', 'Julien', 'Bloc1'),
('julien.solinas@student.vinci.be', NULL, 'SOLINAS', 'Julien', 'Bloc2'),
('julien.wets@student.vinci.be', NULL, 'WETS', 'Julien', 'Bloc1'),
('junior.maduka@student.vinci.be', NULL, 'MADUKA', 'Junior', 'Bloc3'),
('kadir.dagyaran@student.vinci.be', NULL, 'DAGYARAN', 'Kadir', 'Bloc1'),
('kamil.arszagivelharszagi@student.vinci.be', NULL, 'ARSZAGI VEL HARSZAGI', 'Kamil', 'Bloc2'),
('kamil.kowalczyk@student.vinci.be', NULL, 'KOWALCZYK', 'Kamil', 'Bloc1'),
('kawtar.oumghar@student.vinci.be', NULL, 'OUMGHAR', 'kawtar', 'Bloc1'),
('kei-jyu.hama@student.vinci.be', NULL, 'HAMA', 'Kei-Jyu', 'Bloc1'),
('kevin.heylbroeck@student.vinci.be', NULL, 'HEYLBROECK', 'Kevin', 'Bloc2'),
('kevin.merovallas@student.vinci.be', NULL, 'MERO VALLAS', 'Kevin', 'Bloc1'),
('kevin.tang@student.vinci.be', NULL, 'Tang', 'Kevin', 'Bloc1'),
('khalil.benazzouz@student.vinci.be', NULL, 'BENAZZOUZ', 'Khalil', 'Bloc1'),
('klevis.xhakollari@student.vinci.be', NULL, 'XHAKOLLARI', 'Klevis', 'Bloc1'),
('kodjo.adegnon@student.vinci.be', NULL, 'ADEGNON', 'Kodjo', 'Bloc3'),
('konstantin.romanov@student.vinci.be', NULL, 'ROMANOV', 'Konstantin', 'Bloc3'),
('kyrill.tircher@student.vinci.be', NULL, 'TIRCHER', 'Kyrill', 'Bloc2'),
('lancelot.dewoutersdebouchout@student.vinci.be', NULL, 'de WOUTERS de BOUCHOUT', 'Lancelot', 'Bloc2'),
('laurent.batsle@student.vinci.be', NULL, 'BATSLÉ', 'Laurent', 'Bloc3'),
('leo.descamps@student.vinci.be', NULL, 'DESCAMPS', 'Léo', 'Bloc1'),
('lionel.ovaert@student.vinci.be', NULL, 'OVAERT', 'Lionel', 'Bloc3'),
('liseta.carcani@student.vinci.be', NULL, 'CARCANI', 'Liseta', 'Bloc1'),
('logan.bauduin@student.vinci.be', NULL, 'BAUDUIN', 'Logan', 'Bloc1'),
('logan.bourez@student.vinci.be', NULL, 'BOUREZ', 'Logan', 'Bloc1'),
('loic.defosse@student.vinci.be', NULL, 'Defossé', 'Loïc', 'Bloc1'),
('loic.stevens@student.vinci.be', NULL, 'STEVENS', 'Loïc', 'Bloc3'),
('loic.willems@student.vinci.be', NULL, 'WILLEMS', 'Loic', 'Bloc1'),
('lopodi.gaza@student.vinci.be', NULL, 'GAZA', 'Lopodi', 'Bloc1'),
('lorenzo.lapage@student.vinci.be', NULL, 'LAPAGE', 'Lorenzo', 'Bloc1'),
('lorenzo.lauricella@student.vinci.be', NULL, 'LAURICELLA', 'Lorenzo', 'Bloc1'),
('louis.vanaken@student.vinci.be', NULL, 'VAN AKEN', 'Louis', 'Bloc1'),
('loury.jacob@student.vinci.be', NULL, 'JACOB', 'Loury', 'Bloc1'),
('lucas.malmport@student.vinci.be', NULL, 'Malmport', 'Lucas', 'Bloc1'),
('lukas.greif@student.vinci.be', NULL, 'GREIF', 'Lukas', 'Bloc1'),
('macblair.ballecer@student.vinci.be', NULL, 'BALLECER', 'Mac Blair', 'Bloc1'),
('majd.fahmi@student.vinci.be', NULL, 'FAHMI', 'Majd', 'Bloc1'),
('malo.misson@student.vinci.be', NULL, 'MISSON', 'Malo', 'Bloc1'),
('mamadou.cisse@student.vinci.be', NULL, 'CISSÉ', 'Mamadou', 'Bloc2'),
('marc.deburlet@student.vinci.be', NULL, 'de BURLET', 'Marc', 'Bloc3'),
('marc.meganck@student.vinci.be', NULL, 'MEGANCK', 'Marc', 'Bloc1'),
('marco.amory@student.vinci.be', NULL, 'AMORY', 'Marco', 'Bloc1'),
('marcos.garciaaugusto@student.vinci.be', NULL, 'GARCIA AUGUSTO', 'Marcos', 'Bloc2'),
('martin.d’hoedt@student.vinci.be', NULL, 'D’HOEDT ', 'Martin', 'Bloc1'),
('martin.kutzner@student.vinci.be', NULL, 'KUTZNER', 'Martin', 'Bloc1'),
('martin.techy@student.vinci.be', NULL, 'TECHY', 'Martin', 'Bloc3'),
('mathieu.descantonsdemontblanc@student.vinci.be', NULL, 'DESCANTONS de MONTBLANC', 'Mathieu', 'Bloc3'),
('mathieu.marcq@student.vinci.be', NULL, 'MARCQ', 'Mathieu', 'Bloc1'),
('mathieu.steenput@student.vinci.be', NULL, 'STEENPUT', 'Mathieu', 'Bloc3'),
('max.marin@student.vinci.be', NULL, 'Marin', 'Max', 'Bloc1'),
('maxime.demaubeuge@student.vinci.be', NULL, 'DE MAUBEUGE', 'Maxime', 'Bloc3'),
('maxime.denuit@student.vinci.be', NULL, 'DENUIT', 'Maxime', 'Bloc2'),
('maxime.pirlet@student.vinci.be', NULL, 'PIRLET', 'Maxime', 'Bloc2'),
('maxime.poelaert@student.vinci.be', NULL, 'POELAERT', 'Maxime', 'Bloc1'),
('maxime.verwilghen@student.vinci.be', NULL, 'VERWILGHEN', 'Maxime', 'Bloc3'),
('mehdi.ibnlfassi@student.vinci.be', NULL, 'IBNLFASSI', 'Mehdi', 'Bloc1'),
('melissa.strauven@student.vinci.be', NULL, 'STRAUVEN', 'Mélissa', 'Bloc3'),
('meriam.mzoughi@student.vinci.be', NULL, 'MZOUGHI', 'Meriam', 'Bloc2'),
('michael.andre@student.vinci.be', NULL, 'ANDRE', 'Michael', 'Bloc2'),
('michel.debroux@student.vinci.be', NULL, 'De Broux', 'Michel', 'Bloc2'),
('mickael.marlard@student.vinci.be', NULL, 'MARLARD', 'Mickael', 'Bloc2'),
('mike.gaillet@student.vinci.be', NULL, 'GAILLET', 'Mike', 'Bloc3'),
('milenko.vorkapic@student.vinci.be', NULL, 'VORKAPIC', 'Milenko', 'Bloc3'),
('mohamed.hassouni@student.vinci.be', NULL, 'HASSOUNI', 'Mohamed', 'Bloc1'),
('mohammed.chairibounekoub@student.vinci.be', NULL, 'Chairi Bounekoub', 'Mohammed', 'Bloc1'),
('mohammed.elkhattabi@student.vinci.be', NULL, 'EL KHATTABI', 'Mohammed', 'Bloc1'),
('morgan.bossin@student.vinci.be', NULL, 'BOSSIN', 'Morgan', 'Bloc1'),
('mustafa.alp@student.vinci.be', NULL, 'ALP', 'Mustafa', 'Bloc3'),
('nathan.ayele@student.vinci.be', NULL, 'AYELE', 'Nathan', 'Bloc2'),
('nawfal.boujtat@student.vinci.be', NULL, 'BOUJTAT', 'Nawfal', 'Bloc1'),
('nestor.debiesme@student.vinci.be', NULL, 'Debiesme', 'Nestor', 'Bloc1'),
('nicolas.bertolini@student.vinci.be', NULL, 'BERTOLINI', 'Nicolas', 'Bloc2'),
('nicolas.chapelle@student.vinci.be', NULL, 'CHAPELLE', 'Nicolas', 'Bloc1'),
('nicolas.christodouloudegraillet@student.vinci.be', NULL, 'CHRISTODOULOU de GRAILLET', 'Nicolas', 'Bloc2'),
('nicolas.delannoy@student.vinci.be', NULL, 'DELANNOY', 'Nicolas', 'Bloc1'),
('nicolas.gasia@student.vinci.be', NULL, 'GASIA', 'Nicolas', 'Bloc1'),
('nicolas.lecoq@student.vinci.be', NULL, 'LECOQ', 'Nicolas', 'Bloc1'),
('nicolas.lorphelin@student.vinci.be', NULL, 'LORPHELIN', 'Nicolas', 'Bloc1'),
('nicolas.marcq@student.vinci.be', NULL, 'Marcq', 'Nicolas', 'Bloc1'),
('nicolas.oste@student.vinci.be', NULL, 'OSTE', 'Nicolas', 'Bloc3'),
('nicolas.tremerie@student.vinci.be', NULL, 'Tremerie', 'Nicolas', 'Bloc1'),
('nicolas.vangelder@student.vinci.be', NULL, 'van GELDER', 'Nicolas', 'Bloc1'),
('nolan.vanmoortel@student.vinci.be', NULL, 'VANMOORTEL', 'Nolan', 'Bloc2'),
('olivier.degreve@student.vinci.be', NULL, 'DEGRÈVE', 'Olivier', 'Bloc2'),
('othmane.echagdalizahri@student.vinci.be', NULL, 'ECHAGDALI ZAHRI', 'Othmane', 'Bloc1'),
('otman.lachkar@student.vinci.be', NULL, 'LACHKAR', 'Otman', 'Bloc1'),
('patrick.bikorimana@student.vinci.be', NULL, 'BIKORIMANA', 'Patrick', 'Bloc1'),
('patrick.mazur@student.vinci.be', NULL, 'MAZUR', 'Patrick', 'Bloc2'),
('patrycjusz.dolega@student.vinci.be', NULL, 'DOLEGA', 'Patrycjusz', 'Bloc3'),
('paul-edouard.fouquet@student.vinci.be', NULL, 'FOUQUET', 'Paul-Edouard', 'Bloc1'),
('pawel.jalbrzykowski@student.vinci.be', NULL, 'JALBRZYKOWSKI', 'Pawel', 'Bloc1'),
('philipp.shevtchenko@student.vinci.be', NULL, 'SHEVTCHENKO', 'Philipp', 'Bloc3'),
('philippe.dragomir@student.vinci.be', NULL, 'DRAGOMIR', 'Philippe', 'Bloc3'),
('philippe.giuge@student.vinci.be', NULL, 'GIUGE', 'Philippe', 'Bloc3'),
('pierre-paul.gaillet@student.vinci.be', NULL, 'GAILLET', 'Pierre-Paul', 'Bloc2'),
('pierre.michiels@student.vinci.be', NULL, 'MICHIELS', 'Pierre', 'Bloc1'),
('pierric.cotton@student.vinci.be', NULL, 'COTTON', 'Pierric', 'Bloc3'),
('quentin.denis@student.vinci.be', NULL, 'DENIS', 'Quentin', 'Bloc2'),
('quentin.gilmart@student.vinci.be', NULL, 'GILMART', 'Quentin', 'Bloc2'),
('quocdat.nguyen@student.vinci.be', NULL, 'NGUYEN', 'Quoc Dat', 'Bloc3'),
('rachid.asli@student.vinci.be', NULL, 'ASLI', 'Rachid', 'Bloc2'),
('rachid.mabrouk@student.vinci.be', NULL, 'MABROUK', 'Rachid', 'Bloc1'),
('ralph.urbach@student.vinci.be', NULL, 'URBACH', 'Ralph', 'Bloc1'),
('risaci-deogratias.faizi@student.vinci.be', NULL, 'FAIZI', 'Risaci-Deogratias', 'Bloc1'),
('robert.woronko@student.vinci.be', NULL, 'WORONKO', 'Robert', 'Bloc2'),
('robin.lefebvre@student.vinci.be', NULL, 'LEFEBVRE', 'Robin', 'Bloc1'),
('robin.louis@student.vinci.be', NULL, 'LOUIS', 'Robin', 'Bloc1'),
('rocco.cauchi@student.vinci.be', NULL, 'CAUCHI', 'Rocco', 'Bloc1'),
('roland.bura@student.vinci.be', NULL, 'BURA', 'Roland', 'Bloc2'),
('romain.descamps@student.vinci.be', NULL, 'DESCAMPS', 'Romain', 'Bloc2'),
('romain.donck@student.vinci.be', NULL, 'DONCK', 'Romain', 'Bloc1'),
('romain.duvillier@student.vinci.be', NULL, 'DUVILLIER', 'Romain', 'Bloc3'),
('romain.grimmonpre@student.vinci.be', NULL, 'GRIMMONPRÉ', 'Romain', 'Bloc2'),
('romain.vanlithaut@student.vinci.be', NULL, 'VAN LITHAUT', 'Romain', 'Bloc2'),
('romain.weynand@student.vinci.be', NULL, 'WEYNAND', 'Romain', 'Bloc1'),
('roman.skubiszewski@student.vinci.be', NULL, 'SKUBISZEWSKI', 'Roman', 'Bloc2'),
('romaric.honorez@student.vinci.be', NULL, 'HONOREZ', 'Romaric', 'Bloc1'),
('rubain.kamegnesonwabo@student.vinci.be', NULL, 'KAMEGNESON WABO', 'Rubain', 'Bloc1'),
('sacha.maricau@student.vinci.be', NULL, 'MARICAU', 'Sacha', 'Bloc1'),
('said.imran@student.vinci.be', NULL, 'IMRAN', 'Said', 'Bloc1'),
('salim.bouchbouk@student.vinci.be', NULL, 'Bouchbouk', 'Salim', 'Bloc1'),
('sam.ndagano@student.vinci.be', NULL, 'NDAGANO', 'Sam', 'Bloc3'),
('sami.barchid@student.vinci.be', NULL, 'BARCHID', 'Sami', 'Bloc2'),
('sami.farhat@student.vinci.be', NULL, 'FARHAT', 'Sami', 'Bloc1'),
('samir.bacha@student.vinci.be', NULL, 'BACHA', 'Samir', 'Bloc1'),
('samuel.camus@student.vinci.be', NULL, 'CAMUS', 'Samuel', 'Bloc1'),
('sandra.kwibuka@student.vinci.be', NULL, 'KWIBUKA', 'Sandra', 'Bloc1'),
('sebastian.gonzalezmoran@student.vinci.be', NULL, 'GONZALEZ MORAN', 'Sebastian', 'Bloc1'),
('sebastien.croonen@student.vinci.be', NULL, 'CROONEN', 'Sébastien', 'Bloc1'),
('sebastien.pauwels@student.vinci.be', NULL, 'PAUWELS', 'Sébastien', 'Bloc1'),
('sebastien.place@student.vinci.be', NULL, 'PLACE', 'Sébastien', 'Bloc2'),
('sebastien.riga@student.vinci.be', NULL, 'RIGA', 'Sébastien', 'Bloc1'),
('sebastien.serre@student.vinci.be', NULL, 'SERRÉ', 'Sébastien', 'Bloc1'),
('shahadat.sadeque@student.vinci.be', NULL, 'SADEQUE', 'Shahadat', 'Bloc1'),
('shayan.amini@student.vinci.be', NULL, 'AMINI', 'Shayan', 'Bloc1'),
('shenghao.ye@student.vinci.be', NULL, 'YE', 'Sheng Hao', 'Bloc3'),
('simon.guilmot@student.vinci.be', NULL, 'GUILMOT', 'Simon', 'Bloc1'),
('simon.oldenhovedeguertechin@student.vinci.be', NULL, 'OLDENHOVE de GUERTECHIN', 'Simon', 'Bloc2'),
('sohaib.boulbanyousrani@student.vinci.be', NULL, 'BOULBAN YOUSRANI', 'Sohaib', 'Bloc1'),
('sophie.paligot@student.vinci.be', NULL, 'PALIGOT', 'Sophie', 'Bloc1'),
('soufiane.chelaghmi@student.vinci.be', NULL, 'CHELAGHMI', 'Soufiane', 'Bloc1'),
('soufiane.haidour@student.vinci.be', NULL, 'HAIDOUR', 'Soufiane', 'Bloc1'),
('stefan.bogdanovic@student.vinci.be', NULL, 'BOGDANOVIC', 'Stefan', 'Bloc3'),
('tahir.bashir@student.vinci.be', NULL, 'BASHIR', 'Tahir', 'Bloc1'),
('tanguy.snoeck@student.vinci.be', NULL, 'SNOECK', 'Tanguy', 'Bloc2'),
('tarik.yuksel@student.vinci.be', NULL, 'Yuksel', 'Tarik', 'Bloc1'),
('theodor.dimov@student.vinci.be', NULL, 'DIMOV', 'Theodor', 'Bloc3'),
('thibault.andersson@student.vinci.be', NULL, 'ANDERSSON', 'Thibault', 'Bloc1'),
('thibault.devaleriola@student.vinci.be', NULL, 'DEVALERIOLA', 'Thibault', 'Bloc1'),
('thibaut.janssens@student.vinci.be', NULL, 'JANSSENS', 'Thibaut', 'Bloc1'),
('thomas.boon@student.vinci.be', NULL, 'BOON', 'Thomas', 'Bloc1'),
('thomas.lion@student.vinci.be', NULL, 'LION', 'Thomas', 'Bloc1'),
('thomas.ronsmans@student.vinci.be', NULL, 'RONSMANS', 'Thomas', 'Bloc2'),
('thomas.vangelder@student.vinci.be', NULL, 'van GELDER', 'Thomas', 'Bloc2'),
('thomas.verelst@student.vinci.be', NULL, 'Verelst', 'Thomas', 'Bloc1'),
('timothee.bouvin@student.vinci.be', NULL, 'BOUVIN', 'Timothée', 'Bloc2'),
('tom.conneelymcinerney@student.vinci.be', NULL, 'CONNEELY MCINERNEY', 'Tom', 'Bloc1'),
('tomasz.trykozko@student.vinci.be', NULL, 'Trykozko', 'Tomasz', 'Bloc1'),
('tran.nguyen@student.vinci.be', NULL, 'NGUYEN', 'Tran', 'Bloc2'),
('tuan.bui@student.vinci.be', NULL, 'BUI', 'Tuan', 'Bloc1'),
('valentin.delwart@student.vinci.be', NULL, 'DELWART', 'Valentin', 'Bloc2'),
('valentin.desenepart@student.vinci.be', NULL, 'DESÉNÉPART', 'Valentin', 'Bloc2'),
('victor.pierrot@student.vinci.be', NULL, 'Pierrot', 'Victor', 'Bloc1'),
('viken.afsar@student.vinci.be', NULL, 'AFSAR', 'Viken', 'Bloc1'),
('vincent.franchomme@student.vinci.be', NULL, 'FRANCHOMME', 'Vincent', 'Bloc1'),
('vincent.vanrossem@student.vinci.be', NULL, 'VAN ROSSEM', 'Vincent', 'Bloc1'),
('vinhkien.truong@student.vinci.be', NULL, 'TRUONG', 'Vinh Kien', 'Bloc3'),
('virginia.dabrowski@student.vinci.be', NULL, 'DABROWSKI', 'Virginia', 'Bloc2'),
('wim.vanderschueren@student.vinci.be', NULL, 'Van der Schueren', 'Wim', 'Bloc1'),
('xavier.hoffmann@student.vinci.be', NULL, 'HOFFMANN', 'Xavier', 'Bloc3'),
('xavier.mouffo@student.vinci.be', NULL, 'Mouffo', 'Xavier', 'Bloc1'),
('yahya.bennaghmouch@student.vinci.be', NULL, 'BENNAGHMOUCH', 'Yahya', 'Bloc1'),
('yannick.molinghen@student.vinci.be', NULL, 'MOLINGHEN', 'Yannick', 'Bloc3'),
('yannis.manguin@student.vinci.be', NULL, 'MANGUIN', 'Yannis', 'Bloc1'),
('yassin.assecoum@student.vinci.be', NULL, 'ASSECOUM', 'Yassin', 'Bloc1'),
('yassine.elhadouchi@student.vinci.be', NULL, 'EL HADOUCHI', 'Yassine', 'Bloc1'),
('yiwei.chen@student.vinci.be', NULL, 'CHEN', 'Yiwei', 'Bloc1'),
('younes.erraide@student.vinci.be', NULL, 'Erraide', 'Younes', 'Bloc1'),
('younes.moulila@student.vinci.be', NULL, 'MOULILA', 'Younes', 'Bloc1'),
('youness.belhassnaoui@student.vinci.be', NULL, 'BELHASSNAOUI', 'Youness', 'Bloc1'),
('youssef.astitou@student.vinci.be', NULL, 'ASTITOU', 'Youssef', 'Bloc1'),
('youssef.larbi@student.vinci.be', NULL, 'LARBI', 'Youssef', 'Bloc1'),
('yvetteroseline.noulafonkou@student.vinci.be', NULL, 'NOULA FONKOU', 'Yvette Roseline', 'Bloc1'),
('zakaria.lamrini@student.vinci.be', NULL, 'LAMRINI', 'Zakaria', 'Bloc2'),
('zakaria.oulji@student.vinci.be', NULL, 'OULJI', 'Zakaria', 'Bloc1'),
('zineb.elmokadem@student.vinci.be', NULL, 'EL MOKADEM', 'Zineb', 'Bloc1'),
('zohaib.muhammad@student.vinci.be', NULL, 'MUHAMMAD', 'Zohaib', 'Bloc1');

---
-- Scripts sheets
---

INSERT INTO `presences_sheets`(`presence_sheet_id`, `session_id`, `teacher_mail`, `week_id`) VALUES
(1, 195562, 'jeanluc.collinet@ipl.be', 1),
(2, 89944, 'emmeline.leconte@vinci.be', 2),
(3, 55909, 'olivier.choquet@vinci.be', 3);

---
-- Scripts programs
---

INSERT INTO `programs` (`serie_num`, `session_id`) VALUES
(1, 55909),
(1, 89944),
(1, 195562),
(2, 55909);


---
-- Scripts presences
---

INSERT INTO `presences` (`student_mail`, `id_sheet`, `presence`) VALUES
('alexandre.maroun@student.vinci.be', 1, 'x'),
('alexandre.maroun@student.vinci.be', 2, '10'),
('alexandre.maroun@student.vinci.be', 3, 'x'),
('andrea.occhilupo@student.vinci.be', 1, 'x'),
('andrea.occhilupo@student.vinci.be', 2, '18'),
('andrea.occhilupo@student.vinci.be', 3, 'x'),
('antoine.ramelot@student.vinci.be', 1, ''),
('antoine.ramelot@student.vinci.be', 2, '18'),
('antoine.ramelot@student.vinci.be', 3, 'x'),
('florian.timmermans@student.vinci.be', 1, 'x'),
('florian.timmermans@student.vinci.be', 2, '13'),
('florian.timmermans@student.vinci.be', 3, 'x');